# System design — knowledge-driven pipeline
*Generated by Claude*
*Working document. Last updated: 2026-03-18*

---

## 1. Vision

A governed, self-improving development pipeline where analytical work (research, requirements analysis, improvement proposals) feeds structured execution (code generation, testing), and outcomes feed back into a growing knowledge base — with a human approval gate before any execution occurs.

The system is not autonomous. It proposes; humans approve; it executes and reports.

---

## 2. System overview

The system has two hemispheres and a governed boundary between them.

**Analytical hemisphere** — reads from KBs, performs analysis, raises requests:
- Knowledge base management (read/write)
- Research requests (guided web search → KB ingestion)
- Work Package Proposals (WPPs) — scoped improvement proposals
- Requirements analysis and prompt refinement

**Execution hemisphere** — runs approved work, produces artefacts:
- Requirements → unit test → code pipeline (already working)
- Post-execution reporting
- KB write-back (gated)

**The approval gate** — everything raised by the analytical hemisphere lands in a pending queue as a structured report. Nothing executes until manually approved. This is the primary safety and auditability mechanism.

---

## 3. Core artefacts

Every approved and executed work package produces two bound artefacts:

### Statement (markdown, mutable → immutable at close)
The living contract for a work package. Contains:
- Context at proposal time
- Proposal (scope, rationale, resource assessment)
- Method (how it will be executed)
- Running review log (updated as the WPP progresses)
- Post-execution outcome summary

Stays as plain markdown — both human and system auditable. Becomes immutable when the WPP closes.

### Diff (immutable from creation)
The exact code delta. No narrative, no interpretation. Cryptographically linked to its Statement via a hash embedded at close time.

### WorkRecord
The bound pair of Statement + Diff, plus:
- WPP ID
- KB snapshot reference at proposal time
- Approver identity and timestamp
- Weighted project context view at proposal time

The WorkRecord is the atomic unit of system history.

---

## 4. Knowledge base architecture

### Non-monolithic by design
KBs are domain-partitioned. Each domain has its own Qdrant collections, its own embedding strategy, its own decay model, and its own weight tier. Rebalancing artefacts scoped to one KB cannot affect another.

**Planned KB domains:**
| KB | Contents | Status |
|----|----------|--------|
| Requirements KB | Requirements, specifications, validation knowledge | **Prototype — this sprint** |
| Execution KB | Code patterns, diffs, failure/retry history | Planned |
| Research KB | Web-sourced external knowledge | Planned (used by Requirements KB now) |

### Dual storage per KB
Each KB domain uses two stores operated together:

**JSON store** — structured, queryable, authoritative. Holds canonical records with typed fields. Source of truth for relationships and status. Weighted highly in all retrieval contexts.

**Vector store (Qdrant)** — semantic retrieval. Holds embeddings of document content alongside provenance payloads. Advisory weight — informs but does not principally dictate decisions.

### Three collections per KB (requirements domain)
```
requirements_kb/
  ├── requirements    — what the system must do
  ├── specifications  — how the system will do it
  └── validations     — evidence that it did it
```

### Provenance — mandatory on every write
No KB mutation occurs without a provenance entry recording: source, trigger, timestamp, confidence, and WPP reference. This applies equally to research ingestion and rebalancing artefacts.

---

## 5. Project context

A structured record of the system's current self-understanding. Updated after every WorkRecord is absorbed. Carries composite weighting.

**Structural shape:**
```
ProjectContext
  ├── structured_fields
  │     ├── constraints[]        — hard limits, never decay, append-only
  │     ├── goals[]              — weighted by recency + citation frequency
  │     ├── active_modules[]     — superseded by each relevant approved WPP
  │     └── known_risks[]        — severity (human-assigned) × recency decay
  └── narrative_log              — append-only markdown, one entry per WorkRecord
```

**Composite weighting model:**
- Source-based: structured sources carry defined weight; vector sources are advisory
- Type-based: constraints > goals > observations
- Recency: goals and risks decay if uncited; risks compound if repeatedly raised and unresolved
- Explicit: humans can assign weight at review time

**Absorption sequence on WorkRecord close:**
1. Update project context (editorial judgment applied here)
2. KB write-back from updated context
3. Never the reverse — raw artefacts do not write directly to KB

**KB snapshot binding:**
Each WPP captures a reference to the project context state at proposal time. If significant KB updates occur between proposal and execution, the system flags a staleness risk before proceeding.

---

## 6. KB rebalancing loop

The vector KB accumulates bias over time — some concepts become over-represented, others under-represented relative to what the structured record says should matter.

**Mechanism:**
1. Project context + work statement form a query context
2. Query context interrogates the vector KB
3. Delta between vector KB signal and structured record weights is computed
4. Two types of corrective artefacts are generated:
   - **Enforcement artefacts** — reinforce under-represented concepts via additional embeddings
   - **Destruction artefacts** — suppress over-represented concepts via counter-embeddings or reweighting signals
5. Rebalancing artefacts are provenance-logged and reversible — history is preserved, not edited

**Retrieval requirement:**
The rebalancing signal must be respected at query time, not just at embedding time. Qdrant's payload-based filtering and scoring supports this — retrieval weights are applied during ANN search, not as post-processing.

---

## 7. Prototype scope — current sprint

### Goal
Build the first end-to-end slice: web research → KB ingestion → retrieval → requirements prompt refinement.

### Pipeline
```
web search → relevance gate → structured extraction → [JSON store + vector store] → retrieval → prompt refinement
```

### What is being built

**`search_module.py`** — guided web search via Tavily API
- Executes parameterised queries against a topic/domain
- Persists raw results immediately and immutably before any processing
- Deterministic result IDs (hash of url + query) — same URL in different queries produces distinct records
- `SearchRun` and `RawSearchResult` dataclasses form the provenance foundation

**`postprocess_module.py`** — two-stage LLM postprocessing
- Stage 1 (relevance gate): `claude-haiku-4-5-20251001` — binary relevant/irrelevant per result, fast and cheap, all decisions logged for audit
- Stage 2 (structured extraction): `claude-sonnet-4-6` — runs only on gate survivors, extracts typed fields for the JSON KB
- `ExtractedEntry` shape carries both structured fields (for JSON KB) and `embed_text` (for vector KB) — populated from same ingestion event

**`run_research.py`** — guided query runner
- Seed queries for the requirements/specification/validation domain
- Writes per-run entry files and a combined `all_entries.json`
- Query list is the primary dial for domain coverage

### What is not yet built (next steps)
- DB storage module — `all_entries.json` → Qdrant + JSON store
- Knowledge retrieval module — structured + semantic query interface
- Prompt refinement loop — retrieval output → improved requirements prompts
- WPP lifecycle and Statement/Diff artefact generation
- Project context structure and update logic
- Rebalancing loop

---

## 8. Embedding model

**Recommended: Qwen3-Embedding (0.6B → 4B → 8B)**

- Supports Matryoshka Representation Learning (MRL): 4096-dim native, safely truncatable to 1024-dim with ~95% retrieval performance retained
- At 1024 dims, float32: ~4KB per vector. 50k vectors ≈ 200MB before index overhead
- 8B model supports 32k token context — suitable for embedding full WorkRecord statements
- Served via Ollama or vLLM alongside existing generative models — no additional infrastructure

**Prototype shortcut:** start with `0.6B` via Ollama for fast local iteration. Swap to `4B` when extraction quality matters.

---

## 9. Design decisions — key choices and rationale

| Decision | Choice | Rationale |
|----------|--------|-----------|
| Search API | Tavily | Returns cleaned content, not raw HTML — reduces postprocessing noise. 1,000 free searches/month sufficient for prototype. |
| Relevance gate model | Haiku | Binary decision — does not require high capability. Running on every result, cost matters. |
| Extraction model | Sonnet | Runs only on gate survivors. Structured field extraction benefits from higher capability. |
| Raw result persistence | Before postprocessing, immutable | Enables debug/replay without re-running searches. Foundation of provenance model. |
| Structured + vector dual store | Both per KB domain | Structured = authoritative, filterable, weighted. Vector = semantic, advisory. Neither alone is sufficient. |
| Project context update before KB write | Context first | Requires editorial judgment before raw artefacts influence the KB. Prevents unreviewed content contaminating knowledge. |
| Rebalancing via artefacts, not deletion | Enforcement/destruction artefacts | Vector DBs cannot cleanly delete or edit embeddings. Artefact-based correction is non-destructive, auditable, and reversible. |
| Non-monolithic KB | Domain-partitioned collections | Prevents cross-domain noise in retrieval. Scopes rebalancing. Allows different embedding strategies per domain. |
| Human approval gate | Before all execution | System proposes; humans approve; system executes. The gate is the primary safety and auditability mechanism. It is not optional. |

---

## 10. Open questions

- **Project context structure:** hybrid structured object + versioned document is the working assumption, but not yet implemented
- **Constraint initialisation:** how are initial constraints populated — manually authored, or can early WPPs propose them?
- **Narrative log location:** inside project context, or a separate document that project context references? Keeping it separate keeps project context lean and queryable
- **Rebalancing trigger:** what initiates a rebalancing pass — time-based, WPP-triggered, or drift-threshold-triggered?
- **Research request approval:** research is a prerequisite for WPPs, not a sub-type. Does it have a lighter approval path, or the same gate?